<a href="https://colab.research.google.com/github/therealzh/Data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [5]:
ex_dict = {'a':10, '1':1, 'zhouzhan':5} #Curly brackets ในหารบอกว่าเป็น dictionary

In [6]:
ex_dict ['zhouzhan']

5

In [11]:
ex2_dict = {1 : 'one', 2:'two', 3:'three'}

In [12]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิกใน dictionary

In [13]:
ex2_dict[0] = 'zero'

In [14]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่งที่ใช้บ่อย

In [19]:
ex2_dict.keys() #print keys ทั้งหมด

dict_keys([1, 2, 3, 0])

In [17]:
for index in ex2_dict.keys() :
      print(index)

1
2
3
0


In [20]:
ex2_dict.values() #ค่าของkeys (values)ทั้งหมด

dict_values(['one', 'two', 'three', 'zero'])

dictionary เอาไปใช้ร่วมกับ dataframe ของ panda

#Numpy Array (array n dimensions )
ืีnumpy คือ package ที่ทำงานเกี่ยวกับตัวเลข
numpy ---> nnumber + python

In [21]:
import numpy #วิธีเรียกใช้งานpackage

In [26]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[3.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [3.1 0.1 0.3]]


#ชี้ค่าใน numpy

In [27]:
ex_2d_array[1,2] #ชี้ค่าในnumpy 

0.3

In [34]:
list_x = [[5.2,3.0,4.5],[3.1,0.1,0.3]]
print(len(list_x))


2


In [40]:
list_x[1][2] #การชี้ค๋าในlist

0.3

#Operation

In [42]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [3.1 0.1 0.3]]


In [43]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)