<a href="https://colab.research.google.com/github/therealzh/Data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10, '1':1, 'zhouzhan':5} #Curly brackets ในหารบอกว่าเป็น dictionary

In [ ]:
ex_dict ['zhouzhan']

5

In [ ]:
ex2_dict = {1 : 'one', 2:'two', 3:'three'}

In [ ]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิกใน dictionary

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่งที่ใช้บ่อย

In [ ]:
ex2_dict.keys() #print keys ทั้งหมด

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys() :
      print(index)

1
2
3
0


In [ ]:
ex2_dict.values() #ค่าของkeys (values)ทั้งหมด

dict_values(['one', 'two', 'three', 'zero'])

dictionary เอาไปใช้ร่วมกับ dataframe ของ panda

#Numpy Array (array n dimensions )
ืีnumpy คือ package ที่ทำงานเกี่ยวกับตัวเลข
numpy ---> nnumber + python

In [ ]:
import numpy #วิธีเรียกใช้งานpackage

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[3.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [3.1 0.1 0.3]]


#ชี้ค่าใน numpy

In [ ]:
ex_2d_array[1,2] #ชี้ค่าในnumpy 

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[3.1,0.1,0.3]]
print(len(list_x))


2


In [ ]:
list_x[1][2] #การชี้ค๋าในlist

0.3

#Operation

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [3.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex2_2d_array + ex_2d_array

array([[6.2, 3. , 4.5],
       [3.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex2_2d_array - ex_2d_array

array([[-4.2, -3. , -4.5],
       [-3.1, -0.1,  0.7]])

In [ ]:
ex2_2d_array * ex_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

###matrix multiplication (dot product)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [3.1 0.1 0.3]]
[[5.2 3.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = np.dot(ex2_2d_array,ex_2d_array.T) 
print(dot_mat)

[[5.2 3.1]
 [4.5 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-12.389999999999999

###Matrix Slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [3.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [3.1, 0.1]])

###**HW5 เขียน Function คูณ matrix**


1.   (2,3)*(3,2) = X0*Y0
2.   (4,4)*(4,1) = X1*Y1
3.   (2,2)*(2,2) = X2*Y2

In [ ]:
import numpy as np

In [ ]:

#Matrix 2*3 : X0
X0 = np.array([[1,2,7],[3,6,5]])
#Matrix 3*2 : Y0
Y0 = np.array([[9,4],[0,7],[2,4]])
print(f'X0 = {X0} \n\n Y0 = {Y0}')

X0 = [[1 2 7]
 [3 6 5]] 

 Y0 = [[9 4]
 [0 7]
 [2 4]]


In [ ]:
#Matrix 4*4 : X1
X1 =  np.array([[5,8,7,3],[9,1,8,3],[2,3,4,9],[6,4,7,2]])
#Matrix 4*1 :  Y1
Y1 = np.array([[0],[4],[7],[13]])
print(f'X1 = {X1} \n\n Y1 = {Y1}')

X1 = [[5 8 7 3]
 [9 1 8 3]
 [2 3 4 9]
 [6 4 7 2]] 

 Y1 = [[ 0]
 [ 4]
 [ 7]
 [13]]


In [ ]:
#Matrix 2*2 : X2
X2 = np.array([[11,12],[13,14]])
#Matrix 2*2 : Y2
Y2 = np.array([[77,88],[66,99]])
print(f'X2 = {X2} \n\n Y2 = {Y2}')

X2 = [[11 12]
 [13 14]] 

 Y2 = [[77 88]
 [66 99]]


In [ ]:
def mul_mat(x, y) :
  z = [[0 for row in range(len(y[0]))] for col in range(len(y))]
  for i in range(len(x)) :
    for j in range(len(y[0])) :
      for k in range(len(y)) :
        z[i][j] += x[i][k]*y[k][j]
  r = np.matrix(z)
  return r

#**`การคูณ Matrix`**

In [ ]:
print(f' 1. X0*Y0 = {mul_mat(X0,Y0)} \n\n 2. X1*Y1 = {mul_mat(X1,Y1)} \n\n 3. X2*Y2 = {mul_mat(X2,Y2)}')

 1. X0*Y0 = [[23 46]
 [37 74]
 [ 0  0]] 

 2. X1*Y1 = [[120]
 [ 99]
 [157]
 [ 91]] 

 3. X2*Y2 = [[1639 2156]
 [1925 2530]]


In [ ]:
#check
numpy.dot(X1,Y1)

array([[120],
       [ 99],
       [157],
       [ 91]])

### zeros, random

In [1]:
import numpy as np #import numpy แล้วตั้งชื่อเป็น np; npตั้งเป็นอะไรก็ได้ เหมือนกำหนดอักษรให้เขียนง่ายขึ้น

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#ones

In [12]:
np.ones(2)

array([1., 1.])

###Matrix Operation (scalar multiplication)

In [19]:
M_one = np.ones((2,3))

In [20]:
2*M_one

array([[2., 2., 2.],
       [2., 2., 2.]])

###Random

In [29]:
np.random.rand(2)  #ค่าที่ได้จะอยู่ระหว่าง 0-1 // uniform landom

array([0.26211053, 0.44690278])

In [25]:
np.random.randn(2,3) #ค่าที่ได้จะมี meanเป็น 0, variance เป็น 1 // normal distribution

array([[ 0.29304534, -0.75018646,  1.06910457],
       [ 0.52520918, -0.28892821, -0.58924784]])

In [38]:
np.random.choice([1,2,3,127,12],size =2 )

array([12,  2])

In [39]:
np.random.choice([1,2,3,127,12],size =(2,3) )

array([[ 12,   3,   2],
       [  3, 127,   2]])

In [47]:
np.random.choice([1,2,3,127,12],size =(2,3), replace=True )

array([[ 12,  12,   1],
       [127,  12,  12]])

In [58]:
np.random.choice([1,2,3,127,12,8],size =(2,3), replace=False, p= [0.1,0.1,0.1,0.2,0.2,0.3] )

array([[127,   8,   3],
       [ 12,   2,   1]])